// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public class Customer
{
    public int ID_Customer { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public string Contact { get; set; }

    public string Email { get; set; }

    public decimal? Average_feedback { get; set; }

    public int? ID_Role { get; set; }

    public int? ID_Package { get; set; }

    public DateTime? HSD_package { get; set; }

    public virtual ICollection<Boxchat> BoxchatBuyers { get; set; } = new List<Boxchat>();

    public virtual ICollection<Boxchat> BoxchatSellers { get; set; } = new List<Boxchat>();

    public virtual Package ID_PackageNavigation { get; set; }

    public virtual Role ID_RoleNavigation { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}