// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class Order
{
    public int ID_Order { get; set; }

    public int? ID_Ticket { get; set; }

    public string Payment_method { get; set; }

    public string Seller { get; set; }

    public string Buyer { get; set; }

    public decimal? Price { get; set; }

    public int? Quantity { get; set; }

    public string Status { get; set; }

    public DateTime? Shipping_time { get; set; }

    public DateTime? Order_time { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Ticket ID_TicketNavigation { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}