// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class Role
{
    public int ID_Role { get; set; }

    public string Name_role { get; set; }

    public string Role1 { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}