// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class swp1Context : DbContext
{
    public swp1Context(DbContextOptions<swp1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Boxchat> Boxchats { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Request> Requests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Boxchat>(entity =>
        {
            entity.HasKey(e => e.ID_Boxchat).HasName("PK__Boxchat__23A1BC0646EAE1D8");

            entity.ToTable("Boxchat");

            entity.Property(e => e.Chat_content).HasColumnType("text");

            entity.HasOne(d => d.Buyer).WithMany(p => p.BoxchatBuyers)
                .HasForeignKey(d => d.Buyer_ID)
                .HasConstraintName("FK__Boxchat__Buyer_I__66603565");

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Boxchats)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__Boxchat__ID_Tick__6477ECF3");

            entity.HasOne(d => d.Seller).WithMany(p => p.BoxchatSellers)
                .HasForeignKey(d => d.Seller_ID)
                .HasConstraintName("FK__Boxchat__Seller___656C112C");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.ID_Customer).HasName("PK__Customer__2D8FDE5F5F00CC1E");

            entity.ToTable("Customer");

            entity.Property(e => e.Average_feedback).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.Contact)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.HSD_package).HasColumnType("date");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PackageNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ID_Package)
                .HasConstraintName("FK__Customer__ID_Pac__4E88ABD4");

            entity.HasOne(d => d.ID_RoleNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ID_Role)
                .HasConstraintName("FK__Customer__ID_Rol__4D94879B");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.ID_Feedback).HasName("PK__Feedback__7CA05C3F6F939D5F");

            entity.ToTable("Feedback");

            entity.Property(e => e.Comment).HasColumnType("text");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.ID_Order)
                .HasConstraintName("FK__Feedback__ID_Ord__571DF1D5");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.ID_Notification).HasName("PK__Notifica__09D4F1669EB38735");

            entity.ToTable("Notification");

            entity.Property(e => e.Event)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Organization_day).HasColumnType("date");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__Notificat__ID_Ti__619B8048");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.ID_Order).HasName("PK__Order__EC9FA9550668C65E");

            entity.ToTable("Order");

            entity.Property(e => e.Buyer)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Order_time).HasColumnType("datetime");
            entity.Property(e => e.Payment_method)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Seller)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Shipping_time).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__Order__ID_Ticket__5441852A");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.ID_Package).HasName("PK__Package__10A64872CAEBDEEF");

            entity.ToTable("Package");

            entity.Property(e => e.Name_Package)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => new { e.ID_Customer, e.ID_Order }).HasName("PK__Report__634624CACFD28192");

            entity.ToTable("Report");

            entity.Property(e => e.Comment).HasColumnType("text");

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ID_Customer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Report__ID_Custo__5DCAEF64");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ID_Order)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Report__ID_Order__5EBF139D");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => new { e.ID_Ticket, e.ID_Customer }).HasName("PK__Request__9B2D21ED4A708D4C");

            entity.ToTable("Request");

            entity.Property(e => e.History).HasColumnType("text");
            entity.Property(e => e.Price_want).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Requests)
                .HasForeignKey(d => d.ID_Customer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Request__ID_Cust__5AEE82B9");

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Requests)
                .HasForeignKey(d => d.ID_Ticket)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Request__ID_Tick__59FA5E80");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.ID_Role).HasName("PK__Role__43DCD32D6A28D249");

            entity.ToTable("Role");

            entity.Property(e => e.Name_role)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Role1)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Role");
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.ID_Ticket).HasName("PK__Ticket__79F5DC080E32604D");

            entity.ToTable("Ticket");

            entity.Property(e => e.Buyer)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Ticket_History).HasColumnType("text");
            entity.Property(e => e.Ticket_category)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.ID_Customer)
                .HasConstraintName("FK__Ticket__ID_Custo__5165187F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}